### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by ntdkhiem** [GabrielRF/telegram-id#2]
Sorry, I don't understand the syntax of Javascript so I confused on this when I executed "node index.js" or "npm start". I already have the AdminUserID and Token

```
/root/Private/test/TeleShellBot/index.js:4
const { spawn } = require('child_process');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by ntdkhiem** [comment]
wrong one
